import json
from pathlib import Path

RATIONALes = {
    1: "**Correct Answer: Problem-solve potential accessibility issues and modifications needed in the school environment.**\n\n**Why this is right:** Transition conferences that happen before a medically fragile student re-enters school focus on the immediate supports the student will need to access the educational setting safely. The rehab team comes to the table so the school-based providers can understand current strengths/limits, collaborate on seating, mobility, emergency plans, and environmental modifications. IDEA and AOTA school-based practice guidelines call out environmental accessibility as the primary agenda for medical-to-school transition meetings.\n\n**NBCOT is testing:** Can you prioritize functional access when multiple needs compete? The exam wants you to pick the option that ensures safe school participation on day one, not long-range paperwork.\n\n**Why the other options fall short**\n- *Identify IEP goals for the remainder of the academic year:* Long-term academic goals are addressed in scheduled IEP meetings. This transition meeting is about re-entry logistics, not drafting annual goals.\n- *Review functional gains made in rehabilitation:* The rehab summary is shared, but the question asks for the *primary purpose*. Discussing progress informs the conversation, yet the actionable output must be accessibility planning so the child can participate immediately.\n\n**Book / practice anchor:** AOTA School-based Practice Guideline (3rd ed.) and IDEA 2004 both specify that hospital-to-school transition meetings prioritize environmental modifications, emergency procedures, and assistive technology that enable safe access to curriculum.",
    2: "**Correct Answer: Help the child identify ways to discuss concerns with peers and teachers.**\n\n**Why this is right:** Prader-Willi syndrome comes with social and emotional vulnerability. NBCOT expects the OTR to begin with client-centered coaching that builds the student's self-advocacy skills. Helping the child script language for peers and teachers directly addresses the stated barrier (bullying and feeling unheard) and aligns with occupation-based psychosocial intervention.\n\n**Clinical reasoning:** Before escalating to the team you gather the student's voice, validate feelings, and co-create communication strategies (role-play, social stories, assertiveness scripts). This respects IDEA's mandate for student participation in planning and supports social participation goals.\n\n**Why other options miss the mark**\n- *Discuss with the interprofessional team first:* Skipping the student's perspective reduces autonomy and delays equipping the child with immediate coping tools. Team input is useful later but not the first therapeutic move.\n- *Provide opportunities to resolve bullying:* Jumping straight into anti-bullying groups puts the burden on the child without preparatory skill-building and may heighten anxiety.\n\n**Book / practice anchor:** AOTA Occupational Therapy Practice Guidelines for Children and Youth emphasize student-led communication planning as the first step when addressing bullying before systems-level actions.",
    3: "**Correct Answer: Identify a method for color-coding similarly shaped toiletry items.**\n\n**Why this is right:** Cataracts cause decreased contrast sensitivity, glare intolerance, and difficulty identifying items that look alike. High-contrast labeling strategies allow the client to discriminate shampoo vs. conditioner vs. lotion safely during ADLs, supporting independence without surgery.\n\n**Clinical reasoning:** Environmental modifications that increase contrast and tactile cues are first-line OT interventions for low vision. Using brightly colored elastic bands, tactile stickers, or raised paint dots on containers follows AOTA low-vision guidelines for compensatory ADL strategies.\n\n**Why the other options miss:**\n- *Maximize natural light:* Helpful but insufficient alone; cataracts often worsen with glare, and without contrast cues the client still risks confusion.\n- *Provide over-the-counter glasses:* Cataracts reflect lens opacity rather than refractive error, so magnifiers or readers will not restore clarity.\n\n**Book anchor:** Warren and Barstow, Occupational Therapy Interventions for Adults with Low Vision, highlight contrast labeling and tactile cues as evidence-based strategies for cataract-related ADL challenges.",
    7: "**Correct Answer: Define and discuss the relapse-prevention plan the teen recommended.**\n\n**Why this is right:** Family-centered relapse prevention hinges on shared understanding of triggers, coping strategies, and roles. Having the family rehearse the teenager's plan builds buy-in, clarifies expectations, and sets up consistent support at home -- exactly what the question frames as the group goal.\n\n**OT reasoning:** Motivational interviewing and relapse-prevention models (Marlatt and Gordon) emphasize collaborative planning, spotting early warning signs, and agreeing on responses. The OTR facilitates the conversation so caregivers know how to reinforce coping strategies in real time.\n\n**Why the alternatives miss:**\n- *Review group rules about healthy food or drug use:* A rules recap is generic and does not tailor relapse supports to the adolescent's triggers.\n- *Provide calorie-tracking devices:* Nutrition tracking is unrelated to substance-use prevention unless the case specifically involves an eating co-disorder.\n\n**Book anchor:** AOTA Substance Use Disorder practice guidelines describe OT's role in guiding families through relapse-prevention planning, ensuring everyone can implement coping strategies and environmental adjustments.",
    8: "**Correct Answer: Sit at the table with the resident and encourage gentle conversation; ask if needed eyewear, hearing aids, or dentures are in place; ensure the meal matches the prescribed diet/texture.**\n\n**Why this combination works:** The OTR is screening natural self-feeding performance. Best practice is to observe in context, confirm the resident has all personal adaptive devices, and verify the tray aligns with the dysphagia or cardiac diet ordered. These steps establish safety and an authentic performance baseline before providing cues or assistance.\n\n**Clinical reasoning:**\n- Sitting with the resident normalizes the meal, letting you gauge trunk control, utensil handling, and cognitive engagement.\n- Low-vision or sensory aids must be in place to judge true ability; otherwise you are testing impairment, not functional performance.\n- Diet confirmation prevents aspiration or dietary errors common after transitions from hospital to SNF.\n\n**Why the other options wait:**\n- *Mutually enjoyable topics* come later to grade social participation once safety is established.\n- *Hand-over-hand assistance* would skew the screening and is reserved for intervention after you document baseline.\n- *Exploring customs* is valuable for the occupational profile but can be folded into conversation once initial safety checks are complete.\n\n**Book anchor:** Arvedson and Brodsky, plus the AOTA Feeding, Eating, and Swallowing guideline, emphasize verifying equipment, diet orders, and context before scoring self-feeding."
}

path = Path(r"e:/Projects/NBCOT-Clone/src/data/practice-tests/otr-baseline/questions.json")
data = json.loads(path.read_text())
for item in data:
    rationale = RATIONALes.get(item["order"])
    if rationale:
        item["content"] = rationale

path.write_text(json.dumps(data, indent=2))
