name: E2E - Playwright

on:
  push:
    branches: [ main, master, develop, "feat/**", "fix/**" ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Show environment
        run: |
          node -v
          npm -v
          npx playwright --version

      - name: Prepare test database (optional)
        if: ${{ hashFiles('docker-compose.yml') != '' }}
        run: |
          echo "Skipping DB setup by default. Configure as needed or remove this step."

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_SKIP_AUTH: 'false'
          SKIP_AUTH: 'false'
        run: npx playwright test --reporter=line

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 14

      - name: Upload test results folder
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results
            **/test-results/*.json
          retention-days: 14


