name: Questions Check

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run questions-check
        run: npm run questions:check
      - name: Upload validation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: questions-check-results
          path: |
            test-results/questions-check.json
            test-results/**/*.json
          retention-days: 14


